### ISSUE TITLE
Pretrain script

### ISSUE THREAD

**Issue by bujiahao** [microsoft/COCO-LM#9]
Hi,
Thanks for the great work! 
Do u plan to provide the pretrain code and script?

**Comment by yumeng5** [comment]
Hi @bujiahao ,

We will not release the full pretraining code since that part involves copyright issues of other technologies within the company. Would you take a look at [this issue](https://github.com/microsoft/COCO-LM/issues/2) which provides some important function skeletons of pretraining? I hope that would be helpful.

Best,
Yu

**Comment by bujiahao** [comment]
> Hi @bujiahao ,
> 
> We will not release the full pretraining code since that part involves copyright issues of other technologies within the company. Would you take a look at [this issue](https://github.com/microsoft/COCO-LM/issues/2) which provides some important function skeletons of pretraining? I hope that would be helpful.
> 
> Best, Yu

Thanks for ur reply
I will take a look
